name: go-mod-tidy-action
description: Run `go mod tidy` and push a commit
inputs:
  working_directory:
    required: false
    default: ""
  skip_push:
    required: false
    default: false
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{inputs.working_directory}}
      run: go mod tidy

    - shell: bash
      working-directory: ${{inputs.working_directory}}
      run: git add go.mod
    - name: git add go.sum
      shell: bash
      working-directory: ${{inputs.working_directory}}
      run: |
        if [ -f go.sum ]; then
          git add go.sum
        fi

    - shell: bash
      working-directory: ${{inputs.working_directory}}
      if: fromJSON(inputs.skip_push)
      run: |
        if ! git diff --cached --exit-code go.mod; then
          echo "::error ::go.mod is changed. Please run `go mod tidy`"
          exit 1
        fi
    - shell: bash
      working-directory: ${{inputs.working_directory}}
      if: fromJSON(inputs.skip_push)
      run: |
        if [ ! -f go.sum ]; then
          exit 0
        fi
        if ! git diff --cached --exit-code go.sum; then
          echo "::error ::go.sum is changed. Please run `go mod tidy`"
          exit 1
        fi

    - shell: bash
      working-directory: ${{inputs.working_directory}}
      if: "! fromJSON(inputs.skip_push)"
      run: |
        if [ -f go.sum ]; then
          if git diff --cached --exit-code go.mod go.sum; then
            exit 0
          fi
          echo "::error ::go.mod and go.sum are changed. A commit is pushed automatically to update them."
        else
          if git diff --cached --exit-code go.mod; then
            exit 0
          fi
          echo "::error ::go.mod is changed. A commit is pushed automatically to update it."
        fi

        if ! ghcp -v; then
          # https://github.com/int128/ghcp
          echo "::error ::int128/ghcp isn't installed. To push a commit, ghcp is required."
          exit 1
        fi

        branch=${GITHUB_HEAD_REF:-}
        if [ -z "$branch" ]; then
          branch=$GITHUB_REF_NAME
        fi

        if [ -f go.sum ]; then
          ghcp commit -r "$GITHUB_REPOSITORY" -b "$branch" \
            -m "chore(aqua): update go.mod and go.sum" \
            $(git diff --name-only --cached go.mod go.sum)
        else
          ghcp commit -r "$GITHUB_REPOSITORY" -b "$branch" \
            -m "chore(aqua): update go.mod and go.sum" \
            go.mod
        fi

        exit 1
